disabled_rules:
  - trailing_whitespace
  - todo
excluded:
  - Pods
  - MarlinTests
identifier_name:
  excluded: 
    - id
    - a
    - x
    - y
    - i
  allowed_symbols:
    - _
cyclomatic_complexity:
  ignores_case_statements: true
