source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.5'

workspace 'Marlin'
project 'Marlin.xcodeproj'

use_modular_headers!

def common_pods
  pod "Alamofire"
  pod 'geopackage-ios'
  pod 'mgrs-ios'
  pod 'gars-ios'
end

target 'Marlin' do
    common_pods
    target 'MarlinTests' do
      inherit! :search_paths
      common_pods
      pod 'OHHTTPStubs'
      pod 'OHHTTPStubs/Swift'
      pod 'Quick'
      pod 'Nimble'
      pod 'KIF'
    end
end

