source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.5'

workspace 'Marlin'
project 'Marlin.xcodeproj'

use_modular_headers!

def common_pods
  pod "Alamofire"
  pod "Kingfisher"
  pod 'geopackage-ios'
  pod 'mgrs-ios'
  pod 'gars-ios'
  pod 'PROJ', :modular_headers => false
  pod 'MatomoTracker', '~> 7.5'
  pod 'SWXMLHash', '~> 7'
  pod 'SwiftUIIntrospect'
end

target 'Marlin' do
    common_pods
    target 'MarlinTests' do
      inherit! :search_paths
      common_pods
      pod 'OHHTTPStubs'
      pod 'OHHTTPStubs/Swift'
      pod 'KIF'
    end
end

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Marlin/Pods-Marlin-acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |config_name, config_file|
      xcconfig_path = aggregate_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
  
  installer.pods_project.targets.each do |target|
    # Fix Xcode 14 bundle code signing issue
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
